name: helloGithubAction
 
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: 1. 파일 목록 출력
      run: ls -al
    - name: 2. 테스트 코드 실행
      run: python test.py
    - name: 3. 패키지 설치
      run: python -m pip install --upgrade pip
    - name: 4. 필요한 패키지 인스톨
      run: pip install -r requirements.txt
      
