name: crawlingPractice
 
on: 
  schedule: 
    - cron: "*/10 * * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: 1. 파일 목록 출력
      run: ls -al
    - name: 2. pip 업그레이드
      run: python -m pip install --upgrade pip
    - name: 3. 필요한 패키지 인스톨
      run: pip install -r requirements.txt
    - name: 4. 테스트 코드 실행
      run: python test.py
      
