name: helloGithubAction
 
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: 목록 출력
      run: ls -al
    - name: 파이썬 실행!
      run: python test.py
